public class OuterClassOne {
   public class InnerClassOne {
        public void display() {           // Accessing outer class's field
        }
        public class InnerInnerClassOneA {
            public void show() {
            }
        }
        public class InnerInnerClassOneB {
            public void show() {
            }
            public class InnerInnerInnerClassOneB1 {
                public void show() {
                }
            }
            public class InnerInnerInnerClassOneB2 {
                public void show() {
                }
            }
        }
        public class InnerInnerClassOneC {
            public void show() {
            }
        }
    }
}

 
